spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/domainevents
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
